# Generated by Django 2.2 on 2019-04-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cashier_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_layout', to='tds.Layout')),
                ('cashier_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_playlist', to='tds.Playlist')),
                ('firstway_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstway_layout', to='tds.Layout')),
                ('firstway_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstway_playlist', to='tds.Playlist')),
                ('secondway_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondway_layout', to='tds.Layout')),
                ('secondway_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondway_playlist', to='tds.Playlist')),
            ],
        ),
    ]
