# Generated by Django 2.2 on 2019-04-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='station',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
