# Generated by Django 2.2 on 2019-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0002_auto_20190409_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
