# Generated by Django 2.2 on 2019-04-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0003_station_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='layout',
            name='layout',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist',
            field=models.TextField(blank=True),
        ),
    ]
