# Generated by Django 2.2 on 2019-04-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0004_auto_20190409_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sched',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='cashier_layout',
        ),
        migrations.RemoveField(
            model_name='station',
            name='cashier_playlist',
        ),
        migrations.RemoveField(
            model_name='station',
            name='firstway_layout',
        ),
        migrations.RemoveField(
            model_name='station',
            name='firstway_playlist',
        ),
        migrations.RemoveField(
            model_name='station',
            name='secondway_layout',
        ),
        migrations.RemoveField(
            model_name='station',
            name='secondway_playlist',
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlayout', to='tds.Layout')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dplaylist', to='tds.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='displays',
            field=models.ManyToManyField(to='tds.Display'),
        ),
    ]
