# Generated by Django 2.2 on 2019-04-09 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0005_auto_20190409_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='displays',
        ),
        migrations.AddField(
            model_name='display',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='dstation', to='tds.Station'),
            preserve_default=False,
        ),
    ]
