# Generated by Django 2.2 on 2019-04-09 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0006_auto_20190409_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='dstation', to='tds.Station'),
        ),
    ]
