# Generated by Django 2.2 on 2019-04-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0011_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='stationa',
        ),
    ]
