# Generated by Django 2.2 on 2019-04-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0012_remove_display_stationa'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='station',
            field=models.ManyToManyField(to='tds.Station'),
        ),
    ]
