# Generated by Django 2.2 on 2019-04-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0013_display_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='station',
        ),
    ]
