# Generated by Django 2.2 on 2019-04-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0014_remove_display_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
