# Generated by Django 2.2 on 2019-04-09 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0016_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
