# Generated by Django 2.2 on 2019-04-09 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0018_display_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dstation', to='tds.Station'),
        ),
    ]
