# Generated by Django 2.2 on 2019-04-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0021_station_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='way',
            name='station',
        ),
        migrations.AddField(
            model_name='way',
            name='station',
            field=models.ManyToManyField(to='tds.Station'),
        ),
    ]
