# Generated by Django 2.2 on 2019-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0022_auto_20190409_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sched',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
