# Generated by Django 2.2 on 2019-04-10 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0023_auto_20190409_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sched',
            name='station',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tds.Station'),
        ),
    ]
