# Generated by Django 2.2 on 2019-04-10 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0024_auto_20190410_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sched',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tds.Station'),
        ),
    ]
