# Generated by Django 2.2 on 2019-04-10 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0025_auto_20190410_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='tds.Station'),
        ),
    ]
