# Generated by Django 2.2 on 2019-04-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0026_auto_20190410_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sched',
            name='datetime',
        ),
        migrations.AddField(
            model_name='sched',
            name='holiday',
            field=models.BooleanField(default=False, verbose_name='Holiday'),
        ),
        migrations.AddField(
            model_name='sched',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
